### ISSUE TITLE
Arguments after keyword arguments

### ISSUE THREAD

**Issue by mottosso** [BigRoy/pather#3]
[This line](https://github.com/BigRoy/pather/blob/f66a4f08ec6c3780194e3b6b70afd216ce2179c2/pather/core.py#L104%29) looks problematic.

``` python
def ls(pattern, data=None, *args, **kwargs):
    return list(ls_iter(pattern, data, *args, **kwargs))
```

**Comment by BigRoy** [comment]
Fixed with https://github.com/mottosso/pather/commit/24624d98ca80db49d565be36bc4eb67d28f2f075
